---
title: "Howo 2"
author: "smith arthur q"
date: "June 24, 2018"
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r read-csv}
#set.seed(2)
ks = read.csv("ks16.CSV",header=TRUE,stringsAsFactors = FALSE)
#datinp = read.table("Rdata.csv", header=TRUE, stringAsFactors=FALSE, as.is = !stringsAsFactors , sep=",")
#
#
# first cleanup - numeric data getting converted to factors!! Bad...#
#
#
ks$goal = as.numeric(ks$goal)
ks$pledged = as.numeric(ks$pledged)
ks$backers = as.numeric(ks$backers)   # numeric or character best serve our needs?
ks$usd.pledged = as.numeric(ks$usd.pledged)
ks$deadline = as.Date(ks$deadline)
ks$launched = as.Date(ks$launched)

#datinp$b = as.numeric(datinp$b)
#datinp$ctr = with(datinp, as.integer(a/b) )

#summary(pr)  # any weird mean, median?  Data integer, character?  Maybe an outlier?  
#plot(pr$x5)  # visual for outliers?
#cor(pr)  # correlation issues?
#print(pr[100:200,])

```
```{r examine-the-data}
#set.seed(2)
ks2 = read.csv("ks16.CSV",header=TRUE,stringsAsFactors = FALSE)
tech2 = ks2[ks2$category == 'Technology',]
techNoID2 = tech2[,-(1:5)] # cut id name cat mcat currency  
ct2 = techNoID2[,-(9:12)] # cut empty columns x, x1, x2, x3 
#head(ct2)
#summary(ct2)

```

```{r binning}
#...........................
#
# does binning make sense?  
# backers 0, 1 to 10, 11 to 100, more than 100...
# 
justBackers = ct2$backers 
  
breaks = c(0,1,10,100,25000)
cuts = cut(as.numeric(justBackers),breaks)
table(cuts)

```

```{r tree}
#..................................
#
# does a tree make sense to split things into big failure, medium failure, iffy failure
#
library(tree)
tree.k=tree(ct2$state ~ as.factor(ct2$backers),data=ct2)
tree
summary(tree.k)
tree.k$size
tree.k$k

```

```{r categorize-data}
#
# run this if we want to split by major category
#

pub = ks[ks$category == 'Publishing',]
summary(pub)

film = ks[ks$category == 'Film & Video',]
summary(film)

music = ks[ks$category == 'Music',]
summary(music)

food = ks[ks$category == 'Food',]
summary(food)

design = ks[ks$category == 'Design',]
summary(design)

games = ks[ks$category == 'Games',]
summary(games)

comics = ks[ks$category == 'Comics',]
summary(comics)

crafts = ks[ks$category == 'Crafts',]
summary(crafts)

art = ks[ks$category == 'Art',]
summary(art)

photo = ks[ks$category == 'Photography',]
summary(photo)

dance = ks[ks$category == 'Dance',]
summary(dance)

```

```{r just-tech}
#
# sense tech is the closest to "traditional" VC, treat it seperately
#
tech = ks[ks$category == 'Technology',]
summary(tech)
head(tech)
```


```{r save-tech-data}
write.csv(tech, file = "techdata.csv")

```


```{r clean-the-data}
techNoID = tech[,-(1)] # cut id out 
techNoCats = techNoID[,-(2:4)] # cut categories and currency
cleanTech = techNoCats[,-(10:13)] # cut empty colums x, x1, x2, x3, x4
head(cleanTech)

```

```{r prep-to-engineer}
techProjects = dim(cleanTech)
obs = techProjects[1]

#typeof(cleanTech) # what is it?
#class(cleanTech) # what is it?  
#storage.mode(cleanTech) # what is it?  
#length(cleanTech) # how long is it?  
#dim(cleanTech) # matrix?
#attributes(cleanTech) # does it have any metadata?


```

```{r add-3-columns}
#
# since we are predicting failures, do we need to reverse these?
#
believerRatio = rep(1,obs)    # add col for believers per $ (higher ratio means more believers)
hopeRatio = rep(1,obs)        # add col for pledged $ per goal $ (higher ratio means they are TRUE believers )  
hopeSlope = rep(1,obs)        # add col for $ per day (higher ratio means hope is going viral) 
expandedTech = cbind(cleanTech,believerRatio,hopeRatio,hopeSlope) 
dim(expandedTech)
class(expandedTech)

q = expandedTech
#head(q)

```

```{r engineer}
#attributes(q[])

obs = 100
for (i in 1:obs){
  q[i,10] = q[i,7]/q[i,3]             # believerRatio = backers/goal................do more believers/$ matter?  
  q[i,11] = q[i,10]/q[i,3]            # hopeRatio = usd.pledged/goal................do "strong" believers/$ matter? 
  duration = (q[i,2]-q[i,4]) 
  q[i,12] = q[i,9]/as.numeric(duration) # hopeSlope = usd.pledged/deadline-launched...does "faster" uptake matter?  
 
  message(i)
  message(' Faith:',q[i,10])
  message(' Hope: ', q[i,11])
  message(' Speed: ', q[i,12])  
  message('   ')

}

```



