---
title: "project"
author: "smith arthur q"
date: "July 21, 2018"
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r read-csv}
#set.seed(2)
s = read.csv("cleanedData2.CSV",header=TRUE,stringsAsFactors = FALSE)
#

```

```{r prep-to-engineer}
#
# we have many "suspended" projects (1,846)  
# should we delete them?  
# should we treat them as failed?
# should we impute them as successful or failed based on if they met goal
#
# A project may be suspended if our Integrity team uncovers:
# Misrepresentation of support, through self-pledging.
# Misrepresentation or failure to disclose relevant facts about the project or its creator.
# creator provides inaccurate or incomplete user information to Kickstarter or one of our partners.
# characteristics of creator account overlap with the characteristics of backer accounts that pledged to their project.
# party related to the creator is posing as an independent, supportive party in project comments or elsewhere.
# The creator is presenting someone else's work as their own.
# The creator is offering purchased items, claiming to have made them.
# The creator or an affiliated service is spamming potential backers with promotional materials.
# creator repackages a previously-created product, without adding new feature or aims to iterate on the idea in any way.
# The creator has outstanding fulfillment issues related to a previously successful crowdfunding campaign

barplot(prop.table(table(s$state,exclude=NULL)))
#
# relatively few suspended projects (less than one percent = 1,846 out of 376,303)
#

ss = s[s$state == 'successful',]
barplot(prop.table(table(ss$goal,exclude=NULL)))
barplot(prop.table(table(ss$pledged,exclude=NULL)))
barplot(prop.table(table(ss$backers,exclude=NULL)))
#
# how successful look overall
# goal appears to be random
# pledged is right skewed
# backers is right skewed

fl = s[s$state == 'failed',]
barplot(prop.table(table(fl$goal,exclude=NULL)))
barplot(prop.table(table(fl$pledged,exclude=NULL)))
barplot(prop.table(table(fl$backers,exclude=NULL)))
#
# how failed look overall
# goal appears to be random
# pledged is right skewed
# backers is right skewed

sp = s[s$state == 'suspended',]
barplot(prop.table(table(sp$goal,exclude=NULL)))
barplot(prop.table(table(sp$pledged,exclude=NULL)))
barplot(prop.table(table(sp$backers,exclude=NULL)))
#
# how suspended look overall
# goal appears random
# pledged is right skewed
# backers is right skewed

message(" successful - goal")
summary(ss$goal)
message(" failed - goal")
summary(fl$goal)
message(" suspended - goal")
summary(sp$goal)
#
# the mean of goal, for suspendeds is way out of alignment with successful and failed... 
# but the median is in the bounds of successful and failed...

message(" ")
message(" ")
message(" ")

message(" successful - backers")
summary(ss$backers)
message(" failed - backers")
summary(fl$backers)
message(" suspended - backers")
summary(sp$backers)
#
# suspended values do not fall outside the bounds of successful or failed for any statistic
#

```

```{r illogical-backer-pledge-relationships}

bzero = s[(s$backers == 0) & (s$usd_pledged_real > 0) ,]
bzero = bzero[complete.cases(bzero[ , 9:10]),]
summary(bzero)
#  median $ pledged is $152 for backers of 0
```

```{r median-for-illogical-backer-pledge-relationship}

#  so, what is median of backers for pledge of $152??

lowPledge = s[(s$usd_pledged_real > 149) & (s$usd_pledged_real < 160) ,]

barplot(prop.table(table(lowPledge$backers,exclude=NULL)))
summary(lowPledge$backers)

```








