---
title: "SVM for project"
author: "smith arthur q"
date: "August 5, 2018"
output: word_document
---

*******************************************************************************************
*******************************************************************************************
*******************************************************************************************

 Dr. DeVilbiss, the code that we claim to be the best model is found in lines 178 to 193 

 Jennifer,
 Q

*******************************************************************************************
*******************************************************************************************
*******************************************************************************************


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-libraries}

library(e1071)
library(MASS)
library(SparseM)
library(NbClust)
library(caret)
```


```{r read-whole-file}
d = read.csv("FinalData.CSV",header=TRUE,stringsAsFactors = FALSE) # all the data
```


```{r remove-year-one}
start.date = as.Date("12/31/2011", "%m/%d/%Y")
s = d[as.Date((d$launched),"%m/%d/%Y") > start.date,]      # eliminate first year because users developed common approaches

```

```{r subsets-of-data}
set.seed(1)

s.live = s[(s$state == 'live'),]                       # object of live projects
s.film = s[(s$main_category == 'Film & Video'),]       # object of major category, only 'film and video' 

s = s.live
s = s.film

s.live = s.live[(s.live$duration > 29),]               # only capture projects at least 30 days old
```

```{r divide-and-reduce-data}
s = s[!(s$state == 'canceled'),]                       # remove canceled projects - can also treat as failures 
s = s[!(s$state == 'suspended'),]                      # remove suspended projects - skew results 
s = s[!(s$state == 'live'),]                           # remove live projects - for a live prototype  
#s = s[!(s$usd_goal_real >20000),]                      # remove the mega projects - skew results
#s = s[!(s$launched > 12/31/2016 ),]                    # just leave 2017 projects

s$result[s$state == 'failed'] = as.integer(0)          # make result a factor of 0 or 1
s$result[s$state == 'successful'] = as.integer(1)      # make result a factor of 0 or 1

s = s[order(s$ID) , ]                                  # sort the data set to pick a subset for model experimentation

train.i   = sample(1:35000,35000)                      # experiment with 35,000 
subset    = s[train.i,]                                 

train.j   = sample(1:10000,10000)                      # train with 10,000 (big, but not too big to choke R)
train     = subset[train.j,]

train.k   = sample(1:7000,3000)                        # smaller training set...
test      = subset[train.k,]

#rm(s,subset,train.i, train.j,train.k)                  # free up memory!!! 

```


```{r prep-for-tree}

rows = nrow(s)
rows = 100000                     # play around with just 100,000 obs
trainIndex    = sample(rows,rows)  #  some training data
testIndex     = sample(rows,rows)  #  some test data - isnt the right way but good enough to play around
sm.tr         = s[trainIndex,]  
sm.tst        = s[testIndex,]

sm8.tr        = sm.tr[,8]               # get state col only 
sm8.tst       = sm.tst[,8]
s.live8       = s.live[,8]

sm9to11.tr    = sm.tr[,9:11]             # get backers, pledged, and goal
sm9to11.tst   = sm.tst[,9:11]
s.live911     = s.live[,9:11]

sm14to18.tr   = sm.tr[,14:18]            # get all the engeineered cols
sm14to18.tst  = sm.tst[,14:18]
s.live1418    = s.live[,14:18]

sm.tr         = cbind(sm8.tr,sm9to11.tr,sm14to18.tr)   # create training data 
sm.tr         = sm.tr[,(-8)] 

smt.tst       = cbind(sm8.tst,sm9to11.tst,sm14to18.tst)    # create test data 
smt.tst       = smt.tst[,(-8)]

s.live        = cbind(s.live8,s.live911,s.live1418)
s.live        = s.live[,(-8)]

sm.tr         = sm.tr[,(-6)]              # take out the hope slope or the tree is stupid...
smt.tst       = smt.tst[,(-6)]  
s.live        = s.live[,(-6)]
```

```{r tree-model}
library(tree)

tree.sm=tree(sm8.tr~.,data=sm.tr)
tree.sm
cv.sm=cv.tree(tree.sm, FUN=prune.misclass)
names(cv.sm)
cv.sm$size
cv.sm$k

par(mfrow=c(1,2))
plot(cv.sm$size,cv.sm$dev,type="b")
plot(cv.sm$k,cv.sm$dev,type="b")

pruned = prune.misclass(tree.sm, best=9)
plot(pruned, type="uniform")
text(pruned, pretty = 0)

#  run on live data
#tree.pred=predict(pruned,s.live,type="class")
#table(tree.pred,s.live$s.live8)

#plot(tree.pred)

```

```{r cluster-model}
set.seed(1)
train =  train[,-(1:8)]
#summary(train)
train =  train[,-(6:7)]
#summary(train)
train =  train[,-(7:8)]
#summary(train)
res = NbClust(train, diss=NULL, distance = "manhattan", min.nc=2, max.nc=3, method = "complete", index =  "silhouette") 
res$All.index
res$Best.nc

km.out2=kmeans(train,2,nstart=20)
km.out2$centers
km.out2$size

table(km.out2$cluster,train$result)
```
```{r svm-model}
set.seed(1)

train.k   = sample(1:10163,10163)                        # smaller training set...
test      = subset[train.k,]

train$result = as.factor(train$result)


svm.fit = svm(train$result~., data=train, kernel="linear" )   #Error cannot allocate 3.2 Gb vector
summary(svm.fit)
test.pred = predict(svm.fit, test)  
table(test$result, test.pred) 

######################################################################################################
#
#                                       START OF BEST MODEL
#
######################################################################################################

svm.fit = svm(train$result~., data=train, kernel="polynomial" )   #Error cannot allocate 3.2 Gb vector
summary(svm.fit)
test.pred = predict(svm.fit, test)  
table(test$result, test.pred) 

######################################################################################################
#
#                                       END OF BEST MODEL
#
######################################################################################################

svm.fit = svm(train$result~., data=train, kernel="radial" )   #Error cannot allocate 3.2 Gb vector
summary(svm.fit)
test.pred = predict(svm.fit, test)  
table(test$result, test.pred) 

message('radial SVM Specificity - true negatives')

```
